### ISSUE TITLE
Issue on login into the system

### ISSUE THREAD

**Issue by sillyputi** [toffeegz/tall-stack-payroll-management-system#3]
Sir, would like to ask is there any alternative way to login into the system? Because there is no sign up button so I could not  create a new account to access the system.

**Comment by toffeegz** [comment]
Thank you for your message. Regarding your question about the registration function, please note that new accounts are created by our HR admin through the user management feature.

Also, please note that I have just pushed some updates to the main branch. Kindly ask you to perform a pull request to ensure that you have the latest version of the system.

Lastly, you may use the following credentials to log in:
Email: admin@admin.com
Password: password

Please let me know if you have any further questions or concerns. Thank you!

**Comment by sillyputi** [comment]
Great! I able to login through the system.

Thank you for the updates!

**Comment by sillyputi** [comment]
> Thank you for your message. Regarding your question about the registration function, please note that new accounts are created by our HR admin through the user management feature.
> 
> Also, please note that I have just pushed some updates to the main branch. Kindly ask you to perform a pull request to ensure that you have the latest version of the system.
> 
> Lastly, you may use the following credentials to log in: Email: [admin@admin.com](mailto:admin@admin.com) Password: password
> 
> Please let me know if you have any further questions or concerns. Thank you!

Great! I able to login through the system.

Thank you for the updates!

**Comment by sillyputi** [comment]
Hi Sir, would like to ask how the user access the system while the user profile has already created by the admin but the password is not found and the user email is not received any verification email from it.

**Comment by toffeegz** [comment]
> 

Hello, thank you for your question. Currently, in our system, if an admin creates a user profile, the user will not receive a verification email, but the user can use the 'forgot password' feature to reset their password. However, please note that in our upcoming v2 release, we will be adding a new feature that allows users created by admins to receive email verification. Thank you for your patience and understanding.
